### PR TITLE
Bump grpc dependencies and workflow versions

### PR DESCRIPTION
**Pull request by embano1**
- [x] manually bump deps for go modules using grpc
- [x] update github action workflows to enable modules caching to speed up runs (required steps reordering)
- [x] add dependabot configuration to include workflow updates

### CODE REVIEW

**Comment by embano1** [comment]
@lionelvillard @duglin

**Comment by embano1** [comment]
supersedes #911 #912 #913

**Comment by duglin** [comment]
LGTM

**Comment by embano1** [comment]
@duglin I can't merge, so feel free to do so ,)

**Comment by duglin** [comment]
> @duglin I can't merge, so feel free to do so ,)

Well, let's fix that first :-)
https://github.com/cloudevents/sdk-go/pull/915

**Comment by duglin** [comment]
LGTM
ping @lionelvillard for one last quick scan

**Comment by lionelvillard** [comment]
LGTM

**Pull request merged**
