### PR TITLE
[WIP] Package restructuring

### PR DESCRIPTION
**Pull request by lucperkins**
Addresses issue #135

### CODE REVIEW

**Comment by n3wscott** [comment]
I am not a fan of the loss of the pkg directory. The issue was saying just the cloudevents dir because it was redundent.

**Comment by lucperkins** [comment]
@n3wscott Could you clarify what the desired end state is here?

**Comment by n3wscott** [comment]
I would prefer `https://github.com/cloudevents/sdk-go/pkg/cloudevents/*` to be moved to `https://github.com/cloudevents/sdk-go/pkg/*`

I work in a lot of projects that use the pkg dir structure, and it works out really nice for libs like this. Flattening all that is in pkg into the root feels too messy because now you don't have a good place to put the cmd, hack, test and docs dirs.

**Comment by lucperkins** [comment]
@n3wscott In Go libraries, the [`pkg` folder](https://github.com/golang-standards/project-layout/tree/master/pkg) is intended for things that you expect others to actually import and use directly. In the case of the CloudEvents SDK, I don't think there's any intention to have developers actually *use* anything directly from, say, `pkg/client` or `pkg/context`. The `pkg` folder is still in place in this PR only because it's a WIP. The `alias.go` pattern is not one I've encountered and, I believe, runs counter to emergent best practices.

My intention is to flatten everything but the examples into the root folder, as is common in many widely used Go libraries, e.g.:

https://github.com/spf13/cobra
https://github.com/spf13/viper
https://github.com/sirupsen/logrus
https://github.com/steinbacher/goose

I don't mean to be brash. I'm happy to leave things the way that they are. But I do believe that the approach that you suggested is not idiomatic.

**Comment by lucperkins** [comment]
I'm going to close this, although I do think that the current project organization is not in line with Go best practices.

**Pull request closed without merging**
