### PR TITLE
HttpReceiver blocks when receiving non POST request (#610)

### PR DESCRIPTION
**Pull request by lahabana**

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
@lahabana Can you fix the dco?

**Review by slinkydeveloper — APPROVED** [review]
This sounds good to me, @n3wscott can you do another pass?

**Comment by lahabana** [comment]
@slinkydeveloper Done for the DCO and thanks for the review!

**Review by n3wscott — APPROVED** [review]
LGTM

Thanks for the fix!

**Pull request merged**
