### PR TITLE
Make a few comments a bit clearer

### PR DESCRIPTION
**Pull request by duglin**
Minor clean-up following https://github.com/cloudevents/sdk-go/pull/977

### CODE REVIEW

**Review by embano1 — APPROVED** [review]
Thx, realized my review comments didn't really make it during the review of the other PR. Appreciate you taking the time
to fix.

**Comment by embano1** [comment]
Btw: with your fixes and reducing flaky integration tests, should we make them required to pass in CI before merging?

**Comment by duglin** [comment]
> Btw: with your fixes and reducing flaky integration tests, should we make them required to pass in CI before merging?

I don't have a strong opinion on that since I assume we won't merge any PRs that have failing checks regardless of whether they're one of the 'required' ones or not.

**Comment by embano1** [comment]
Reason I ask is that I can approve a change and use auto-merge once CI passes :) Enabling now.

**Comment by duglin** [comment]
I was wondering if that was the reason... I have to then ask... why not require all checks to be required? Would we ever want to merge stuff that had a failing check? If so, I'm not sure why we have a check we don't really care about.

**Comment by embano1** [comment]
> I was wondering if that was the reason... I have to then ask... why not require all checks to be required? Would we ever want to merge stuff that had a failing check? If so, I'm not sure why we have a check we don't really care about.

Most of the checks run super fast, i.e., before a maintainer does a review or when changes are pushed afterwards. But you raise a fair point. Right now, Github seems to have issues though: can't add the integration tests to required checks, so 🤷

**Pull request merged**
