### PR TITLE
Added stan (nats-streaming)

### PR DESCRIPTION
**Pull request by xackery**
This implements https://github.com/nats-io/stan.go as a transport layer based on the existing nats code.

There are a few areas that need cleanup, but first wanted to see if any desire for me to harden and make this a supported transport type.

Thanks!

### CODE REVIEW

**Comment by n3wscott** [comment]
a couple CI issues to take care of

**Comment by n3wscott** [comment]
This is awesome btw. I want to include it.

**Comment by n3wscott** [comment]
Ping on this, any interest in continuing? @xackery

**Comment by xackery** [comment]
I'll see about getting some time, but not promises. I do get comment updates

**Comment by tpihl** [comment]
Hi,

and yes, this would be very useful

**Comment by tpihl** [comment]
@xackery, looks like you’re really close...

**Comment by te-brevik** [comment]
I haven't found a way to contribute to this PR, but I've made a fork that have fast-forwarded the upstream changes on master and modified your PR changes to make it work with the current master. You can find my fork at https://github.com/te-brevik/sdk-go/tree/stan

Let me know if you wan't to include this in your PR, or if I should just create a new one; as I need stan support :)

**Comment by xackery** [comment]
My effort was really just taking nats and emulating it for stan, but, if you have the bandwidth to work and maintain, go for it!

**Comment by dan-j** [comment]
I can pick this up over the course of this week, just handling a few things in NATS first

**Comment by slinkydeveloper** [comment]
@dan-j what if this PR is transformed to implement the new apis in `bindings` module? Then, from bindings, implementing a `Transport` is a matter of using an adapter

**Comment by dan-j** [comment]
Can do, might take a bit longer to familiarise myself with the APIs. 

What's the idea behind implementing transports vs bindings? Are transports going to be deprecated in the future?

**Comment by slinkydeveloper** [comment]
`binding` APIs are designed to improve the efficiency of the sdk for creating middleware applications. They allows direct encoding from one protocol to another, without going through the Event data structure and reducing as much as possible the memory usage.

I'm not sure what's the future of `Transport`, but it will probably remain (maybe with some changes) to have an high level `Client` API on top, like the existing one. Our goal for v2.0 is to have as much as possible bindings implemented, while the transports should just use the [`BindingTransport` adapter](https://github.com/cloudevents/sdk-go/blob/master/pkg/binding/transport.go) (like the [actual amqp transport](https://github.com/cloudevents/sdk-go/tree/master/pkg/cloudevents/transport/amqp))

To start, check out the existing [http](https://github.com/cloudevents/sdk-go/tree/master/pkg/bindings/http) and [amqp](https://github.com/cloudevents/sdk-go/tree/master/pkg/bindings/amqp) implementations, they are well written and designed ot give you the idea of how to implement a binding . If you need any help, get in touch with me on cloud-native.slack.com on #cloudeventssdk channel, I'll be glad to help.

**Comment by dan-j** [comment]
I've re-implemented this using the bindings API as mentioned in the previous comments. Need to finish up with tests and sample commands, but it's pretty much finished.

#322

**Comment by slinkydeveloper** [comment]
Replaced by https://github.com/cloudevents/sdk-go/pull/322

**Pull request closed without merging**
