### PR TITLE
Recover from panic in handler fn

### LINKED ISSUE #584: Recover from panic in handler function
I believe it could be useful to recover from panics in handler functions passed to `client.StartReceiver`.
The fix could be as simple as:
```diff
diff --git a/v2/client/invoker.go b/v2/client/invoker.go
index acd27e4..42eaaa6 100644
--- a/v2/client/invoker.go
+++ b/v2/client/invoker.go
@@ -2,6 +2,7 @@ package client
 
 import (
        "context"
+       "fmt"
 
        "github.com/cloudevents/sdk-go/v2/binding"
        cecontext "github.com/cloudevents/sdk-go/v2/context"
@@ -58,7 +59,17 @@ func (r *receiveInvoker) Invoke(ctx context.Context, m binding.Message, respFn p
 
                // Let's invoke the receiver fn
                var resp *event.Event
-               resp, result = r.fn.invoke(ctx, e)
+               resp, result = func () (resp *event.Event, result protocol.Result) {
+                       err = nil
+                       defer func() {
+                               if r := recover(); r != nil {
+                                       cecontext.LoggerFrom(ctx).Errorf("inovke panicekd: %v", r)
+                                       result = fmt.Errorf("invoke panicked: %v", r)
+                               }
+                       }()
+                       resp, result = r.fn.invoke(ctx, e)
+                       return
+               }()
 
                if respFn == nil {
                        break
```

### PR DESCRIPTION
**Pull request by matejvasek**
resolves #584

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
@n3wscott can you check out the failing test? seems like an issue with `TestBlockingSenderReceiver` test

**Comment by matejvasek** [comment]
There is some 5% tolerance in place in the test, maybe it should be increased?

**Comment by matejvasek** [comment]
@n3wscott when I increased that time tolerance from 5% to 10% the tests are passing.

**Comment by n3wscott** [comment]
> @n3wscott when I increased that time tolerance from 5% to 10% the tests are passing.

thanks, I think the circleci builder machines are not the best. :D

**Comment by n3wscott** [comment]
LGTM

just need to sign that last commit and the DCO will be happy.

**Comment by matejvasek** [comment]
So I should include the `More time tolerance in TestBlockingSenderReceiver` commit?

**Comment by n3wscott** [comment]
I am fine adding more budget to that test, thanks for fixing!

LGTM

**Pull request merged**
