### PR TITLE
Bindings optimization to support binary -> binary + some refactoring

### LINKED ISSUE #262: binding to transfer binary events without allocating an intermediate
The current binding.Message.Event() API creates an intermediate Event object which then must be encoded to be sent by a Sender. Provide an additional API that allows binary events to be transferred without an intermediate Event data structure (analogous to the way Message.Structured() avoids intermediate data structures for structured messages.)

Idea provided by @slinkydeveloper 
Initial proposal #263

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fixes  #262
Depends on #274

## Overview

Starting from @alanconway work (https://github.com/cloudevents/sdk-go/pull/263) I've reorganized a bit the `Message` interface to allow both binary -> binary message passing and structured -> structured. 

The `Encoder` pattern allows to the receiver message to extract informations and to the sender to encode these informations in the right request structure.

I modified both HTTP and AMQP binding implementations to support new interfaces.

## Benchmark

From https://github.com/cloudevents/sdk-go/tree/master/test/benchmark/http

8Kb payload (left is https://github.com/cloudevents/sdk-go/pull/274, right is this patch)
8k

16Kb payload (left is https://github.com/cloudevents/sdk-go/pull/274, right is this patch)
16k

32Kb payload (left is https://github.com/cloudevents/sdk-go/pull/274, right is this patch)
32k

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
HTTP binding now working (with tests too), AMQP still WIP

**Comment by slinkydeveloper** [comment]
AMQP implemented, still some stuff broken because of encoding

**Comment by slinkydeveloper** [comment]
cc @n3wscott @alanconway

**Comment by n3wscott** [comment]
OH MY! this is going to be grand, thanks for looking at this.

**Comment by slinkydeveloper** [comment]
Rebased with master, now it's ready to review :smile:

**Comment by n3wscott** [comment]
LGTM

**Pull request merged**
