### PR TITLE
Add circleci configuration for test automation

### PR DESCRIPTION
**Pull request by markpeek**
Add an initial circleci configuration to automate testing for PR's and showing test results.

### CODE REVIEW

**Comment by n3wscott** [comment]
looks good, should there be a `go mod tidy` step?

**Comment by n3wscott** [comment]
Also thanks!! We really need some automation.

**Comment by markpeek** [comment]
I added a step that would run `go mod tidy` and error if there is a difference. I'm assuming tidy might modify both go.mod and go.sum.

**Comment by n3wscott** [comment]
>I added a step that would run go mod tidy and error if there is a difference. I'm assuming tidy might modify both go.mod and go.sum.

Thanks! We can try it out and roll with the pain if found. :D

**Pull request merged**
