### PR TITLE
wip: play around with stan lifecycle

### PR DESCRIPTION
**Pull request by dan-j**
do not merge, here just to share a diff

### CODE REVIEW

**Comment by dan-j** [comment]
Oops, was meant to create a PR local to my fork, will leave it here for discussion anyway 🤔

**Comment by dan-j** [comment]
@slinkydeveloper I was thinking about our discussion on slack with closing subscriptions vs connections etc and got this prototype running. I need to add tests (and fix the ones I've broken) before it's anywhere near mergeable (hence meaning to create it on my fork), but thought it would be worth your input.

Essentially:

1. `Consumer.OpenInbound()` sets up the subscription and creates an internal channel `subCloser`, and will pause until either `subCloser` or `ctx` is closed.
1. `Consumer.Close()` checks whether or not `subCloser != nil` (i.e. the consumer is running) and if it is, calls `close(subCloser)` which will cause `OpenInbound` to stop.
1. `Consumer.Close()` only closes the underlying connection if it created it in the constructor. (Just spotted a race condition here, but the high-level details are the only important thing for now)

**Comment by slinkydeveloper** [comment]
Is this still valid?

**Comment by dan-j** [comment]
No, I don't think it is valid anymore. I think we answered the questions around who's responsible for closing connections/protocols/client. Will close

**Pull request closed without merging**
