### PR TITLE
Add Cancellation to Pubsub Receive

### PR DESCRIPTION
**Pull request by ian-mi**

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
Can we enable at some point the integration tests for pub sub? like the ones we have for kafka and amqp.

**Comment by ian-mi** [comment]
Yes, I will try to get those working sometime soon.

**Comment by slinkydeveloper** [comment]
@n3wscott ping, you're the pubsub expert :)

**Comment by n3wscott** [comment]
LGTM

**Pull request merged**
