### PR TITLE
fix: support multiple amqp data fields

### PR DESCRIPTION
**Pull request by embano1**
Support multidimensional `data` field in AMQP implementation when converting an AMQP message to a CloudEvent. Writing to AMQP message from CloudEvent remains unchanged because the first slice of `[][]byte` is used to populate the data.

Ref: https://github.com/cloudevents/spec/issues/1275

### CODE REVIEW

**Comment by embano1** [comment]
cc/ @deissnerk

**Comment by embano1** [comment]
cc/ @duglin for review

**Comment by duglin** [comment]
The code change itself looks good w.r.t. the "just concat them" decision.
However, @deissnerk, is there really no way for someone to split the result back into separate data sections? A simple concat w/o any kind of separator seems like it would make it really hard for consumers, no?

**Comment by embano1** [comment]
@deissnerk that's how I understood it as well

**Comment by duglin** [comment]
ok in that case LGTM

**Review by duglin — APPROVED** [review]

**Pull request merged**
