### PR TITLE
Bump the paho mqtt to v0.12

### PR DESCRIPTION
**Pull request by yanmxa**
Reference: https://github.com/eclipse/paho.golang/releases/tag/v0.12.0
Signed-off-by: myan <myan@redhat.com>

### CODE REVIEW

**Comment by duglin** [comment]
All mqtt users will to upgrade too, right?

**Comment by yanmxa** [comment]
Do you mean whether this version is stable? 

It was released last month and contains small fixes/improvements.

**Review by embano1 — APPROVED** [review]
LGTM

**Comment by duglin** [comment]
What's I'm wondering about is this: https://github.com/cloudevents/sdk-go/pull/981/files#diff-1a09a46967bd262e499762fc039a474889783193cc58172b29b3f643afae9511R148
While I understand that paho is only v0.12 (not a v1.0) so things can change, but this breaks existing SDK/mqtt users no?

It still may be ok, but I'd like to make sure we understand the ramifications.... if I'm correct.

**Comment by yanmxa** [comment]
> What's I'm wondering about is this: https://github.com/cloudevents/sdk-go/pull/981/files#diff-1a09a46967bd262e499762fc039a474889783193cc58172b29b3f643afae9511R148 While I understand that paho is only v0.12 (not a v1.0) so things can change, but this breaks existing SDK/mqtt users no?
> 
> It still may be ok, but I'd like to make sure we understand the ramifications.... if I'm correct.

Yes! Users must modify a small amount of "cloudevent-client" initialization code to use the latest MQTT(0.12) SDK.

**Comment by embano1** [comment]
Good 👀 @duglin !

Since it's been a while that we had a release, I also lost track of any potential breaking change we're introducing with the upcoming release. Usually this is mitigated with PR notes and change-log parsing/generation, which we haven't set up in the repo though.

**Comment by duglin** [comment]
LGTM
one last check... @embano1 you're still ok with this, right?

**Review by duglin — APPROVED** [review]

**Comment by duglin** [comment]
ping @embano1 and @lionelvillard for final review

**Review by embano1 — APPROVED** [review]
Someone just needs to keep in mind to add a `BREAKING` notice to the release notes :)

**Pull request merged**
