### PR TITLE
kafka pkg changed to shopify

### PR DESCRIPTION
**Pull request by wxxiong6**
fix: samples kafka  sarama pkg type errors

```
import (
	"context"
	"fmt"
	"log"

	"github.com/IBM/sarama"

	"github.com/cloudevents/sdk-go/protocol/kafka_sarama/v2"
	cloudevents "github.com/cloudevents/sdk-go/v2"
)

func main() {
	saramaConfig := sarama.NewConfig()
	saramaConfig.Version = sarama.V2_0_0_0

	receiver, err := kafka_sarama.NewConsumer([]string{"127.0.0.1:9092"}, saramaConfig, "test-group-id", "test-topic")
```

### CODE REVIEW

**Comment by embano1** [comment]
Please provide an issue/description for this PR.

**Comment by duglin** [comment]
I'm confused, I thought it moved away from Shopify. That url even redirects to ibm.

**Comment by wxxiong6** [comment]
Have added, can merge。

**Comment by embano1** [comment]
Please provide justification for the package import changes. Your description does not explain the change. Please see https://github.com/cloudevents/sdk-go/blob/main/CONTRIBUTING.md for how to contribute to this project.

**Comment by duglin** [comment]
@wxxiong6 please reply to https://github.com/cloudevents/sdk-go/pull/983#issuecomment-1804298434

**Comment by embano1** [comment]
Closing since activity seems suspicious. Please see our CONTRIBUTING guide for how to contribute to this project.

**Pull request closed without merging**
