### PR TITLE
claim.Messages() seems returning nil sometime, avoid nil pointer

### PR DESCRIPTION
**Pull request by nbajaj90**
claim.Messages() seems returning nil sometime, avoid nil pointer

### CODE REVIEW

**Review by rahulchheda — APPROVED** [review]
LGTM

**Comment by duglin** [comment]
Can you please sign your commit and check on the test failures?

**Comment by duglin** [comment]
Actually, it looks like the error may not be PR specific. So just signing your commits should be enough

/LGTM

@lionelvillard  ?

**Comment by nbajaj90** [comment]
@lionelvillard PTAL

**Pull request merged**
