### PR TITLE
update go-nats to the latest release version and update go mod

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by n3wscott** [comment]
What version go golang are you using? I do not understand why this is not building.

**Comment by thinkerou** [comment]
@n3wscott fixed.
`go.opencensus.io/exporter/prometheus` -> `contrib.go.opencensus.io/exporter/prometheus`

**Comment by thinkerou** [comment]
> What version go golang are you using?

```
➜  sdk-go git:(mod) go version
go version go1.12 darwin/amd64
```

**Comment by n3wscott** [comment]
Looks like the ci wants you to run `go mod tidy` and we will be able to update the libs.

**Comment by n3wscott** [comment]
going to close and reopen to see if the CI will rerun.

**Comment by thinkerou** [comment]
ci output:
```
#!/bin/bash -eo pipefail
go mod tidy && git diff --exit-code go.{mod,sum}
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/nats-io/nats-server/v2 v2.0.0
go: downloading github.com/Azure/go-autorest/autorest v0.2.0
go: downloading google.golang.org/appengine v1.5.0
go: downloading github.com/stretchr/testify v1.3.0
go: downloading github.com/fortytw2/leaktest v1.3.0
go: downloading github.com/Azure/azure-sdk-for-go v30.1.0+incompatible
go: downloading github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: downloading github.com/Azure/go-autorest/autorest/adal v0.1.0
go: downloading github.com/Azure/go-autorest/autorest/mocks v0.1.0
go: downloading github.com/Azure/go-autorest/tracing v0.1.0
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/Azure/go-autorest/logger v0.1.0
go: downloading github.com/Azure/go-autorest/autorest/date v0.1.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading contrib.go.opencensus.io/exporter/ocagent v0.4.12
go: downloading github.com/census-instrumentation/opencensus-proto v0.2.0
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.8.5
go: downloading github.com/nats-io/jwt v0.2.6
go: downloading github.com/Azure/go-autorest/autorest/validation v0.1.0
go: downloading github.com/Azure/go-autorest/autorest/to v0.2.0
diff --git a/go.sum b/go.sum
index c73ae1c..eb03614 100644
--- a/go.sum
+++ b/go.sum
@@ -37,6 +37,7 @@ github.com/census-instrumentation/opencensus-proto v0.2.0 h1:LzQXZOgg4CQfE6bFvXG
 github.com/census-instrumentation/opencensus-proto v0.2.0/go.mod h1:f6KPmirojxKA12rnyqOA5BBL4O983OfeGPqjHWSTneU=
 github.com/client9/misspell v0.3.4/go.mod h1:qj6jICC3Q7zFZvVWo7KLAzC3yx5G7kyvSDkc90ppPyw=
 github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
+github.com/davecgh/go-spew v1.1.1 h1:vj9j/u1bqnvCEfJOwUhtlOARqs3+rkHYY13jYWTU97c=
 github.com/davecgh/go-spew v1.1.1/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
 github.com/dgrijalva/jwt-go v3.2.0+incompatible h1:7qlOGliEKZXTDg6OTjfoBKDXWrumCAMpl/TFQ4/5kLM=
 github.com/dgrijalva/jwt-go v3.2.0+incompatible/go.mod h1:E3ru+11k8xSBh+hMPgOLZmtrrCbhqsmaPHjLKYnJCaQ=
Exited with code 1
```
but no anything output on my macOS, sorry, I don't know how fix it.

**Comment by thinkerou** [comment]
Now ci is right, but I run `go mod tidy` on my macOS to generate `go.sum` does't the same as ci generated `go.sum`.

**Comment by n3wscott** [comment]
Weird, I have the same version of go.

**Pull request merged**
