### PR TITLE
relative .pb.go generation, go_package set to package name

### PR DESCRIPTION
**Pull request by jnorman-us**
addresses https://github.com/cloudevents/sdk-go/issues/962

In the **.proto** file, `option go_package` is used for pointing to the generated pb package. I'm importing the **cloudevents.proto** for creating gRPC handlers functions that accept a CloudEvent, but the import breaks because `go_package` points to a local path. 

I set `go_package` to `github.com/cloudevents/sdk-go/binding/format/protobuf/v2/pb` which Go is able to resolve. However generation was broken until I found this **protoc** flag in a [StackOverflow answer](https://stackoverflow.com/a/62920647): `--go-opts=paths=source_relative`.

I also changed the package name to `io.cloudevents.v1`, just like the format [here](https://github.com/cloudevents/spec/blob/d0eccd083b875e1619162dd3ad41e26ac6e2c40f/cloudevents/formats/cloudevents.proto#L11). Package names are [supposed to be unique](https://protobuf.dev/programming-guides/style/#packages) so there aren't collisions when importing multiple protobuf files.

### CODE REVIEW

**Comment by duglin** [comment]
SGTM but I know next to nothing about proto, so @embano1 and @lionelvillard for review

**Comment by duglin** [comment]
rebase needed

**Comment by duglin** [comment]
Rebase needed

**Comment by duglin** [comment]
Sorry, another rebase needed

**Comment by duglin** [comment]
ping @embano1 @lionelvillard

**Comment by duglin** [comment]
@jnorman-us can you please rebase this?
ping @embano1 for review.

**Review by embano1 — APPROVED** [review]

**Pull request merged**
