### PR TITLE
vote to add embano1 as a maintainer

### PR DESCRIPTION
**Pull request by duglin**
ping @lionelvillardand @markpeek 

The vote will last 1 week, or until Lionel and Mark have voted (whichever comes first)

### CODE REVIEW

**Comment by duglin** [comment]
oops, sorry @dan-j I forgot that you're a maintainer too

**Comment by lionelvillard** [comment]
LGTM

**Comment by duglin** [comment]
A week had passed... all voters voting "yes".  Welcome aboard @embano1

**Comment by embano1** [comment]
Yeahhhh 🥳

**Pull request merged**
