### PR TITLE
Remove vi swp file

### LINKED ISSUE #1019: `protocol.go.swp` file for http protocol?
As part of this bump:
* https://github.com/cloudevents/sdk-go/pull/958

This file got introduced:
* https://github.com/cloudevents/sdk-go/blame/main/v2/protocol/http/.protocol.go.swp

This now seems to cause some update issues on Knative eventing:
* https://github.com/knative/eventing/pull/7697#issuecomment-1953921426

### PR DESCRIPTION
**Pull request by duglin**
Fixes #1019

### CODE REVIEW

**Comment by duglin** [comment]
/cc @matzew 
thanks for noticing!

**Comment by duglin** [comment]
@embano1 @lionelvillard for a quick/easy review

**Review by matzew — APPROVED** [review]
LGTM

**Comment by matzew** [comment]
@duglin are you doing a 2.15.1 patch release for this?

**Review by embano1 — APPROVED** [review]

**Comment by duglin** [comment]
New release: https://github.com/cloudevents/sdk-go/releases/tag/v2.15.1

**Pull request merged**
